### ISSUE TITLE
shows only one image

### ISSUE THREAD

**Issue by MelanieMaMann** [bitmotion/typo3-image-gallery#10]
I installed the extension in TYPO3 9.5.9, in list mode it only shows one image. I tried it in 2 different installations. I also checked the generated HTML Code.

**Comment by FlorianWessels** [comment]
Hi Melanie,

could you please provide more information on this issue?
For example:
* How many file collections have you selected?
* Is the detail view located on the same page or do you have a dedicated detail page?
* Do the file collection has more than one file?
* ...

Thanks,
Flo
