### ISSUE TITLE
Flexform Override

### ISSUE THREAD

**Issue by Haruki-Mortis** [bitmotion/typo3-image-gallery#8]
Hey guys,
today I updated to the latest version.

Is it possible to override the ControllerActions.xml ?

In the old extension I just had to override:

Folder: my_extension/Configuration/TCA/Overrides/tt_content.php

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue(
    'bmimagegallery_list',
    'EXT:my_extension/path/to/flexform/ControllerActions.xml'
);`

It doesn't work in the new one.

It's very important for me and I hope you can help me.

**Comment by bmheins** [comment]
At first glance, this sounds to me like your extension gets loaded **before** typo3-image-gallery. Do you have a set a dependency (or a suggestion) on typo3-image-gallery in your extension's ext_emconf.php? If not, try this first.

**Comment by Haruki-Mortis** [comment]
Thanks for the fast answer.
The dependency in ext_emconf is already set.
And my extension is the last included one.
If I delete the ControllerActions.xml call from your extension, my extended flexform is loaded.
I can't find the reason why your extension overrides the call.

And yes, an hour ago the same override worked with the older version.

**Comment by bmheins** [comment]
Right now, I don't have any idea. I'd log the calls to `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPiFlexFormValue()` to see in which order they are made.

**Comment by Haruki-Mortis** [comment]
Solution:
I moved the config into my ext_tables.php, everything works fine now.

Have a nice time and thanks for your awesome extension.
