### ISSUE TITLE
Error in Typo3 9.5.5 (but not 8.7.24)

### ISSUE THREAD

**Issue by fabrikatur** [bitmotion/typo3-image-gallery#9]
Hi.

I'm getting this error in a Typo3 9.5.5 (composer setup). I have the same version of the extension runing on 8.7.24 ('old school' installation setup with Extension Manager) without any issues:

Argument 1 passed to Bitmotion\BmImageGallery\Domain\Model\Dto\CollectionInfo::setPreview() must be an instance of TYPO3\CMS\Core\Resource\FileInterface, boolean given, called in ...../public/typo3conf/ext/bm_image_gallery/Classes/Domain/Model/Dto/CollectionInfo.php on line 28

Any ideas where I/it might be going wrong?

Thanks. If there is any further information I can provide, feel free to ask, of course!

Cheers

**Comment by fabrikatur** [comment]
Hi.
A short follow-up. I did a clean install of Typo3 v9.5.5 on my local machine with the most basic TS-setup and bm_image_gallery as the only extension. I get the same error.

**Comment by FlorianWessels** [comment]
Hi,

thanks for using our extension. Your described problem sounds like a broken FileCollection or something like that. May you please check your plug in settings (especially the assigned FileCollections)? 
We can not reproduce this issue with the given information.

Thanks,
Flo

**Comment by fabrikatur** [comment]
Hi Flo. Thanks for your reply. I couldn't see anything wrong and tried with several FileCollections, new and old (as well as a clean install as mentioned above). The values stored in the DB also looked fine and where no different than in Version 8). As I have to finish the project shortly I have had to move to a different plug-in. But I will surely come back and look at this more closely when I have time, as I liked the straightforward implementation a lot.
Kind regards.

**Comment by SadlerJohnson** [comment]
Hi,

I get something similar in Typo3 9.5.9 (on Windows):

Argument 1 passed to Bitmotion\BmImageGallery\Domain\Model\Dto\CollectionInfo::setPreview() must implement interface TYPO3\CMS\Core\Resource\FileInterface, boolean given, called in C:\inetpub\wwwroot\archive_9\typo3conf\ext\bm_image_gallery\Classes\Domain\Model\Dto\CollectionInfo.php on line 28 | TypeError thrown in file C:\inetpub\wwwroot\archive_9\typo3conf\ext\bm_image_gallery\Classes\Domain\Model\Dto\CollectionInfo.php in line 76.

I get this error with a new collection based on a sys_category. Folder based collections seem to work
